### ISSUE TITLE
make时遇到了问题

### ISSUE THREAD

**Issue by xsk0206** [FudanMPL/SecMML#10]
make时遇到了以下问题，请问应该怎么解决？
`collect2: error: ld returned 1 exit status

CMakeFiles/MPL.dir/build.make:353: recipe for target 'MPL' failed
make[2]: *** [MPL] Error 1
CMakeFiles/Makefile2:114: recipe for target 'CMakeFiles/MPL.dir/all' failed
make[1]: *** [CMakeFiles/MPL.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by wqruan** [comment]
你好，请问可以提供完整的错误日志吗？

**Comment by xsk0206** [comment]
抱歉，之前忘了回复，下面是完整的日志
`[ 43%] Building CXX object CMakeFiles/queqiao.dir/Constant_wrapper.cpp.o
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:12:68: error: ‘B’ was not declared in this scope
         .def_property_readonly_static("B", [](py::object) { return B; })
                                                                    ^
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:13:68: error: ‘D’ was not declared in this scope
         .def_property_readonly_static("D", [](py::object) { return D; })
                                                                    ^
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:14:68: error: ‘L’ was not declared in this scope
         .def_property_readonly_static("L", [](py::object) { return L; })
                                                                    ^
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:15:69: error: ‘D2’ was not declared in this scope
         .def_property_readonly_static("D2", [](py::object) { return D2; })
                                                                     ^~
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:16:69: error: ‘CH’ was not declared in this scope
         .def_property_readonly_static("CH", [](py::object) { return CH; })
                                                                     ^~
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:17:69: error: ‘IE’ was not declared in this scope
         .def_property_readonly_static("IE", [](py::object) { return IE; })
                                                                     ^~
CMakeFiles/queqiao.dir/build.make:75: recipe for target 'CMakeFiles/queqiao.dir/Constant_wrapper.cpp.o' failed
make[2]: *** [CMakeFiles/queqiao.dir/Constant_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:89: recipe for target 'CMakeFiles/queqiao.dir/all' failed
make[1]: *** [CMakeFiles/queqiao.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by xsk0206** [comment]
抱歉，之前忘了回复，下面是完整的错误日志
[ 43%] Building CXX object CMakeFiles/queqiao.dir/Constant_wrapper.cpp.o
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:12:68: error: ‘B’ was not declared in this scope
         .def_property_readonly_static("B", [](py::object) { return B; })
                                                                    ^
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:13:68: error: ‘D’ was not declared in this scope
         .def_property_readonly_static("D", [](py::object) { return D; })
                                                                    ^
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:14:68: error: ‘L’ was not declared in this scope
         .def_property_readonly_static("L", [](py::object) { return L; })
                                                                    ^
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:15:69: error: ‘D2’ was not declared in this scope
         .def_property_readonly_static("D2", [](py::object) { return D2; })
                                                                     ^~
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:16:69: error: ‘CH’ was not declared in this scope
         .def_property_readonly_static("CH", [](py::object) { return CH; })
                                                                     ^~
/home/xsk/下载/SecMML/Constant_wrapper.cpp: In lambda function:
/home/xsk/下载/SecMML/Constant_wrapper.cpp:17:69: error: ‘IE’ was not declared in this scope
         .def_property_readonly_static("IE", [](py::object) { return IE; })
                                                                     ^~
CMakeFiles/queqiao.dir/build.make:75: recipe for target 'CMakeFiles/queqiao.dir/Constant_wrapper.cpp.o' failed
make[2]: *** [CMakeFiles/queqiao.dir/Constant_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:89: recipe for target 'CMakeFiles/queqiao.dir/all' failed
make[1]: *** [CMakeFiles/queqiao.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wqruan** [comment]
你好，这个问题在我们最新版的代码中已经解决了，请你fork一下代码的当前版本在重新尝试编译。

**Comment by xsk0206** [comment]
> 您好，谢谢您的回复。这个问题在我们最新版的代码中已经解决了，请您fork一下代码的当前在尝试尝试编译。

谢谢，我在Ubuntu18.04里还存在同样的问题，但我在Ubuntu20.04里已经编译成功了。
同时又遇到了新的问题，当运行`queqiao.py`或`./MPL`，输入索引时，出现了如下问题：
函数运算符（）输入的行值或列值超出范围
![QQ截图20220221201839](https://user-images.githubusercontent.com/62367781/154953978-0efcc905-2c91-4941-98ea-1f00074fbbcd.png)

**Comment by wqruan** [comment]
![1645511480(1)](https://user-images.githubusercontent.com/63643853/155075586-7138bd4a-a94e-40ff-a04e-4f0c4b1117d4.png)
感谢您的回复，由于github的仓库中没有数据集，所以需要根据Dataset目录中的指示将MNIST数据集放到Dataset目录中再尝试运行。

**Comment by xsk0206** [comment]
OK,我已经运行成功了。
非常感谢您的耐心回答！

**Comment by wqruan** [comment]
感谢您的反馈意见。我们已经在dataset/mnist目录下添加了自动下载数据集的脚本，并且更新了readme文档，为用户运行项目提供方便。
