### ISSUE TITLE
BGW协议的实现在哪

### ISSUE THREAD

**Issue by deadlywing** [FudanMPL/SecMML#4]
请问源码里关于BGW协议的实现是在哪里？好像没有专门的实现类？
想要了解一下这方面的实现细节，麻烦指点一下，谢谢！

**Comment by leojiang199611** [comment]
BGW协议的实现是在MathOp.h/cpp中，将BGW协议的每一种计算包装到模块化的算子之中，并进行迭代调用。

参考论文：Round-Efficient Protocols for Secure Multiparty Fixed-Point Arithmetic
链接：https://www.researchgate.net/profile/Octavian-Catrina/publication/326652429_Round-Efficient_Protocols_for_Secure_Multiparty_Fixed-Point_Arithmetic/links/5b5b0d7b458515c4b24b6a1e/Round-Efficient-Protocols-for-Secure-Multiparty-Fixed-Point-Arithmetic.pdf
